#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
CGO_CFLAGS="${CGO_CFLAGS:-} -Wno-return-local-addr" go build -trimpath -buildvcs=true -tags "netgo osusergo sqlite_omit_load_extension" -ldflags "-X github.com/PastureStack/catalog-service/cmd.VERSION=$VERSION -s -w" -o bin/catalog-service-sqlite
# Production binary needs to be fully static
CGO_ENABLED=0 go build -trimpath -buildvcs=true -tags "nosqlite netgo" -ldflags "-X github.com/PastureStack/catalog-service/cmd.VERSION=$VERSION -s -w" -o bin/catalog-service
