#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running validation

export CGO_CFLAGS="${CGO_CFLAGS:-} -Wno-return-local-addr"
echo Running: go vet
go vet -mod=vendor -tags=test ./...
# echo Running: golint
# for i in ${PACKAGES}; do
#     if [ -n "$(golint $i | grep -v 'should have comment.*or be unexported' | tee /dev/stderr)" ]; then
#         failed=true
#     fi
# done
# test -z "$failed"
echo Running: go fmt
unformatted=$(find . -path './vendor' -prune -o -path './.git' -prune -o -name '*.go' -type f -print0 \
    | xargs -0 gofmt -l)
test -z "$(printf '%s' "$unformatted" | tee /dev/stderr)"
