[tox]
envlist=flake8, py314

[testenv]
package=skip
install_command=python -I -m pip install --no-index --find-links=/opt/catalog-service-wheelhouse {opts} {packages}
deps=-rrequirements.lock
changedir=core
commands=py.test --durations=20 {posargs}

[testenv:flake8]
deps=-rrequirements.lock
changedir={toxinidir}
commands=flake8 core
